title: Lucky Cache
baseline: ars longa, vita brevis
description: Backlog stuff
baseurl: /
canonicalurl: false
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
